name: visual_editor
description: A rich text editor supporting mobile and web (Demo App @ visualspace.app)
version: 0.0.3
#author: Visual Space, Adrian Moisa
homepage: https://visualspace.app
repository: https://github.com/visual-space/visual-editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.2.0
  image_picker: ^0.8.5
  photo_view: ^0.13.0
  quiver: ^3.1.0
  string_validator: ^0.3.0
  url_launcher: ^6.1.0
  pedantic: ^1.11.1
  video_player: ^2.4.0
  characters: ^1.2.0
  youtube_player_flutter: ^8.0.0
  diff_match_patch: ^0.4.1
  i18n_extension: ^4.2.1
  gallery_saver: ^2.3.2
  device_info_plus: ^3.2.3
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: null