name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Installing Flutter because it's easier to generate .lcov files for test coverage
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Analyze the code for linting errors
      - name: Flutter analyze
        run: flutter analyze

      - name: Install dependencies
        run: flutter pub get

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. 
      # Note that Flutter projects will want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test --coverage

      - uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
          verbose: true # optional (default = false)